### ISSUE TITLE
PrivateKey example is misleading.

### ISSUE THREAD

**Issue by prurph** [Finanzchef24-GmbH/tunnel-ssh#15]
I initially had an issue with `privateKey` because I naively thought I could pass a string path to a privkey, but this would throw `Error: Cannot parse privateKey: Unsupported key format` from inside ssh2. I ultimately got it to work by using fs and loading the file that way. It might be worth mentioning this in the examples. 

(I'd happily submit a PR using this technique in conjunction with a new field like `privateKeyPath` or something but that would add a dependency on `fs`.)

Thanks for this package!

**Comment by agebrock** [comment]
Hi @prurph,

thanks for the information i'll update the example.

privateKey - mixed - Buffer or string that contains the host private key (OpenSSH format). (Required) Default: (none)

**Comment by agebrock** [comment]
Done.
