### ISSUE TITLE
Reverse

### ISSUE THREAD

**Issue by stefano055415** [Finanzchef24-GmbH/tunnel-ssh#20]
can I do a tunnel reverse?

**Comment by agebrock** [comment]
Sorry you can't do a reverse tunnel right now. But we will release a package for reverse tunneling soon.

**Comment by samueleaton** [comment]
The script for `reverse` is not included in the `index`. The `reverse` method is undefined. Is it not ready yet? Why is it in the readme? Thank you

**Comment by agebrock** [comment]
Are you using the latest stable version ?

**Comment by samueleaton** [comment]
Ahh. I see the problem. For some reason it installed the beta. I didn't specify it to do that.  thanks
