### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by esnunes** [Finanzchef24-GmbH/tunnel-ssh#21]
Hi,

I'm using tunnel-ssh in a project and I found a critical issue on it, luckily the issue was already fixed however it's been a while since you don't generate a new version. Considering the commits after version 1.1.0 have breaking changes can you publish version 2.0.0 with all fixes?

In the meanwhile I will be pointing directly to your git repository (master branch).

Thanks!

**Comment by agebrock** [comment]
Hi there, should not be a big thing i guess. Where do you see the breaking changes ? 
Well i am prepare version 2.0.0 carefully since we have some ideas to improve the integration of the tunnel.

**Comment by esnunes** [comment]
Hi @agebrock,

The commit I'm really interested in is 188ef5f6393c52e9e1fcc9415fe8740eb5d3df4f which is a breaking change due to the fact that it changes the current behaviour of the library by emitting an event instead of throwing an uncaught exception.

 thank you for the fast reply!

**Comment by agebrock** [comment]
I hope v2 will do the trick.
