### ISSUE TITLE
Error after connection but not caught be .on('error')

### ISSUE THREAD

**Issue by ikb42** [Finanzchef24-GmbH/tunnel-ssh#24]
Hi

I am getting an error after a connection is successfully connected.  I am pretty sure the host is closing the connection, which is fine, but the error is not being caught in the .on error.

```
tunnel(config, function(){
   // I get here
}).on('error', function(error){
  // I dont get here
})
```

This is what I get as output when the app crashed:
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:874:11)
    at TCP.onread (net.js:544:26)
```

**Comment by agebrock** [comment]
Hi there in the current master version tunnel returns the tcp server, so if your ssh client throws an error your server is not affected. This will change in future. 

Maybe stupid but not an error ;) 

Feel free to check the next alpha, to see how the error handling works over there.

**Comment by ikb42** [comment]
Thanks but a little over my head at this point, could you advise what I can try to catch this error before my app crashes?
