### ISSUE TITLE
how to connect to remote mysql 

### ISSUE THREAD

**Issue by SunLn** [Finanzchef24-GmbH/tunnel-ssh#25]
Sorry to trouble you .

Usually , I login in my reomte machine with ```ssh test ``` , and do some job with mysql .But now I want to do this job in my local machine . I try to make it work , but I have trouble .

My ssh config is
```
Host test
    HostName 121.201.1.111
    User test
    Port 12528
    IdentityFile ~/.ssh/id_rsa
```

My remote mysql config is 

```
    host: 'localhost',
    user: 'db_test',
    password: 'db_password',
    database: 'db_name',
```

And all my code is here

```
var tunnel = require('tunnel-ssh');
var  mysql = require('mysql');
  var server = tunnel({
      host: '121.201.1.111',
      dstPort: 12528
    }, function (error, result) {
      if(error) {
        return console.log(error)
      }
      // This is ok ,  
      console.log('connected',result);

       // this is not work
      var connection = new mysql.createConnection({
        host: 'localhost',
        database: "db_name",
        user: "db_test",
        password: "db_password"
      });

      var sql = "select count(*) as total from accounts  ";
     
      connection.query(sql, function(err, rows, fields) {
        if (err) {
            console.log(err);
            return ;
        }
        console.log(rows)
      });
  });
```

I can connect with my ssh machine ,but i can't connect with mysql .  What the problem is ?

The error is like below , when i changed mysql host from  localhost to 121.201.1.111
```
{ [Error: connect ETIMEDOUT]
  errorno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  fatal: true }
```
or below ,  when the  host is localhost 

```
[Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'db_test'@'localhost' (using password: YES)]
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlState: '28000',
  fatal: true }
```

Hope you can help me . Thanks a lot .

**Comment by agebrock** [comment]
Well it looks like you have problems with the authentification. 
you should check your user settings from your mysql. Maybe you need to connect via 127.0.0.1 

Maybe you can use some gui like navicat to figure out your configuration. 
Sorry can't  help you any further here.
