### ISSUE TITLE
Encrypted private key detected, but no passphrase given

### ISSUE THREAD

**Issue by alexcroox** [Finanzchef24-GmbH/tunnel-ssh#26]
```
var sshTunnel = this.tunnel({
        host: 'xxxx',
        sshPort: 22,
        dstPort: 3305,
        username: 'xxxx',
        privateKey: require('fs').readFileSync('/Users/alex/.ssh/id_rsa'),
        keepAlive: true
}, function(error, result) {

        console.log('Connected to SSH mysql tunnel', result);
});
```

Throws `Error: Encrypted private key detected, but no passphrase given`

**Comment by agebrock** [comment]
You should be able to use the option: 
passphrase - string - For an encrypted private key, this is the passphrase used to decrypt it. Default: (none)

**Comment by alexcroox** [comment]
Ah thanks, is that documented anywhere? Can't see it in the README or the very different documentation on https://www.npmjs.com/package/tunnel-ssh
