### ISSUE TITLE
TypeError: Object #<Object> has no method 'then'

### ISSUE THREAD

**Issue by scriby** [Finanzchef24-GmbH/tunnel-ssh#27]
```
TypeError: Object #<Object> has no method 'then'
    at Object.createTunnel [as reverseTunnel] (/Users/scriby/sourcecode/test/node_modules/tunnel-ssh/lib/reverse.js:7:45)
```

Line 7 of reverse.js is `return cfg.setReverseDefaults(userConfig).then(function(config) {`.

As far as I can tell setReverseDefaults does not return a promise, so this code errors.

**Comment by agebrock** [comment]
You are using the stable release of tunnel-ssh, only the development release is using promises right now.

I already realized that npm shows the alpha docs, sorry for the confusion.  
To fix your problem refer to the stable docs at : https://github.com/Finanzchef24-GmbH/tunnel-ssh#reverse-tunnel.

```
tunnel.reverse({
  username: 'root',
  dstHost: '127.0.0.1',
  dstPort: 3000,
  localPort: 8000,
  host: 'remote.machine.io'
}, function() {
  console.log(arguments);
});
```
