### ISSUE TITLE
config,sshPort not used

### ISSUE THREAD

**Issue by chippawah** [Finanzchef24-GmbH/tunnel-ssh#28]
Trying to connect to a remote RethinkDB server on Compose.io. Compose gives a specific port to connect to the ssh server. In a bash command like compose@somecloudserver.com -p XXXXX. I thought I could use the sshPort config variable like this 
```
uiConfig =
  privateKey: key
  username: username
  sshPort: sshPort
  host: host
  srcHost: composeConfig.ip
  srcPort: composeConfig.uiPort
  dstPort: localConfig.uiPort
  dstHost: localConfig.ip
  keepAlive: true
uiTunnel = tunnel uiConfig, (e, uiTunnel)->
  if e
    console.log 'TUNNEL ERROR >>>>', e.message
  else
    console.log 'UI TUNNEL CONNECTED'
```

When the server connects I get 
`Error: getaddrinfo ENOTFOUND compose@cloudserver.com compose@cloudserver.com:22`

Is this because config.sshPort is defaulting to port 22?

**Comment by agebrock** [comment]
You need to remove the username from the hostname. (getaddrinfo => hostname can't be resolved)
The sshPort is working, but you are right about the error message ... it shows port 22 even if another port is used,  i'll report the error to the ssh2 lib.
