### ISSUE TITLE
Shutdown Tunnel

### ISSUE THREAD

**Issue by arkrozycki** [Finanzchef24-GmbH/tunnel-ssh#32]
How do you shutdown a tunnel? I'd like to be able to open a tunnel, run a mysql/mongo query, get the results, and shutdown the tunnel. 

I didn't see any methods in index.js to provide such a feature, thoughts?

**Comment by agebrock** [comment]
Hi @arkrozycki this is a major feature from ssh tunnel. 
ssh tunnel will close the tunnel if you close the connection to the mysql / mongo.

Just make sure you don't use the keepAlive option.
