### ISSUE TITLE
Apparent tunnel() callback inconsistency

### ISSUE THREAD

**Issue by damolina-ms** [Finanzchef24-GmbH/tunnel-ssh#33]
Samples in documentation define callback as:

`var server = tunnel({host: '172.16.0.8', dstPort: 3306}, function (error, result) {`

but tunnel() code calls the callback as  (result, error):

```
  try {
    var config = createConfig(configArgs);
  } catch ( e ) {
    if (callback) {
      callback(null, e);
    } else {
```

**Comment by agebrock** [comment]
Good point i will look into it.

**Comment by agebrock** [comment]
Fixed in r4.
