### ISSUE TITLE
migration from v2 to v3

### ISSUE THREAD

**Issue by todojs** [Finanzchef24-GmbH/tunnel-ssh#36]
Please, we need help to how use the new version 3 because the API is changed without notice.

```
var tunnel = require('tunnel-ssh');
var config = {
    username:'root',
    password:'secret',
    host:'remote.mysql.server.com',
    port:3306
}

tunnel(config, function(e, sshTunnel){
    //Now, you should be able to connect to the tunnel via localhost:3336.
});
```

This code is now:

```
var tunnel = require('tunnel-ssh');
var config = {
    username:'root',
    password:'secret',
    host:'remote.mysql.server.com',
    port:3306
}

tunnel.tunnel(config, function(e, sshTunnel){
    //Now, you should be able to connect to the tunnel via localhost:3336.
});
```

**Comment by ignasbernotas** [comment]
I completely agree, this is the first time I'm building something that needs to create an ssh tunnel to connect to a remote mysql server and I'm really struggling since the documentation isn't really sufficient. I found this lib, which I thought to be a nice abstraction layer, but at the moment I going through the source code to figure out how it works which is taking a lot more time than it should :/

Also, npm installed v3 for me. Which means that the docs in the master branch are completely outdated. v3 docs aren't up to date as well.

If I manage to figure it out, i'll definitely submit a PR with a few examples and some info how to use it.

**Comment by agebrock** [comment]
Please note that version3 is currently in the development branch. You will find a READMEv3.md there.
But anyway, i see your point and will come up with a solution for that very soon.

**Comment by ignasbernotas** [comment]
@agebrock READMEv3 isn't up to date with the development branch either :/

**Comment by agebrock** [comment]
Ok folks i have a solution to fix that problem. 
We will jump from Version 2 to 4. Version 4 will include the current know bugfixes and will be compatible to Version 2. (except the callback response) 

The main feature from Version 3 is moving to its own module. 
I hope that will remove the confusion in near future.

I expect the release within this week.

**Comment by frogbandit** [comment]
@agebrock @todojs Has there been a change in versions recently? Previously I have been doing this with success: 

`tunnel.tunnel(config, function(e, sshTunnel){
});`

But now that doesn't seem to work at all. I checked and my version is 3.2.1-beta.

**Comment by agebrock** [comment]
No we did not do changes in released versions (before r4) 

i am pretty sure you need to remove the first tunnel .. tunnel export should be a function. 
 
Please update to release 4.0.0. If you have any trouble let me know..

**Comment by frogbandit** [comment]
@agebrock When I do npm install tunnel-ssh, it installs only version 3.2.1-beta. How do I install version 4.0.0?

**Comment by frogbandit** [comment]
@agebrock When I just do:`tunnel` instead of `tunnel.tunnel`, it gives me this error: 

```
tunnel(config, function(e, sshTunnel) {
^

TypeError: tunnel is not a function
```

**Comment by agebrock** [comment]
@frogbandit we published the project right now to npm. You should be able to update as you would with every package. Let me know if you have any more trouble.
