### ISSUE TITLE
Syntax changed?

### ISSUE THREAD

**Issue by frogbandit** [Finanzchef24-GmbH/tunnel-ssh#40]
Before a few weeks ago, I used `tunnel.tunnel` to map remote port to localhost. However, now the docs suggest to do just `tunnel`. However, when I just do `tunnel` instead of `tunnel.tunnel`, it gives me this error: 

```
tunnel(config, function(e, sshTunnel) {
^

TypeError: tunnel is not a function
```

However, when I use `tunnel.tunnel` instead, it doesn't give a syntax error -- but, the callback in the function is not called at all.

I'm using version 3.2.1-beta. Is this a version issue?

**Comment by agebrock** [comment]
Yes it is, please update to version4.
