### ISSUE TITLE
"user" vs "username" config option in README.md

### ISSUE THREAD

**Issue by timbowhite** [Finanzchef24-GmbH/tunnel-ssh#41]
Hi, there are a couple of typos in the README.md examples. The **user** config option should be **username**, ie:

Under "Config example":
```
    var config = {
      user:'root',
      host:sshServer,
      port:22,
...
```
and under "Sugar configuration":

```
    var config = {
      user:'root',
      dstHost:destinationServer,
      dstPort:27017
    };
```
If you pass the **user** config option and not the **username** config option, the following is used by tunnel-ssh instead:

```
username: env.TUNNELSSH_USER || env.USER || env.USERNAME,
```
Which obviously may lead to authentication failures.

Thanks.

**Comment by agebrock** [comment]
Wow thanks a lot for that finding. I'll fix that in no time.
