### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by Reggino** [Finanzchef24-GmbH/tunnel-ssh#6]
Hi,

Thank you for this, this is awesome. 

Two minor things:

- In README.md, an example ```sshConfig``` is given with a property called ```passphrase```. That should be ```password``` to work properly.

- And from NPM there is no direct link to this Git-repo, that would be nice too!

**Comment by agebrock** [comment]
Hi Reggino,

thanks for the tip about the missing npm information, i'll fix this in the next minor.

The config property "passphrase" is correct as far as i can see. 
You should use passphrase only if you are providing a key created with a passphrase.
If you use username / password for authentication you never need a passphrase.

**Comment by Reggino** [comment]
Thanks @agebrock, you are completely right. I am not familiar with ```mscdex/ssh2``` and i made an assumption based on the example set me on the wrong foot here.

**Comment by agebrock** [comment]
Np i guess the 1.0.0 description is even worse, you can still use username and password ;)
