### ISSUE TITLE
Tunnel causes mysql connection to not close properly

### ISSUE THREAD

**Issue by jarwol** [Finanzchef24-GmbH/tunnel-ssh#8]
See https://github.com/felixge/node-mysql/issues/1029.

**Comment by agebrock** [comment]
Thx @jarwol, i'll investigate this weekend.

**Comment by agebrock** [comment]
Can you confirm that 1.0.0 is working for you ?

**Comment by jarwol** [comment]
Confirmed.  conn.end now executes its callback, and there is no required tunnel.close() call in order to end the script.  Thanks!

**Comment by agebrock** [comment]
Nice, thx,
